name: Dev - CI/CD
 
on:

  push:
    branches: [ development ]
    paths-ignore:
    - ".github/workflows/**"  
  
  workflow_dispatch:

jobs:

  sonar:
  
    runs-on: self-hosted
    if: ${{ github.ref == 'refs/heads/development' }}
    steps:
      - uses: actions/checkout@v2
          
      - name: Sonar
        uses: luizhpriotto/action_images@sonarscannercli-v2.1
        env:
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST: http://sonar.sme.prefeitura.sp.gov.br/
          
      - name: send failure message
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: -571051431
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            💥 Failed in ${{ github.ref_name	}}!
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}            
            Repository: ${{ github.repository }}            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            Actions: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
         
  build:

    runs-on: self-hosted
    if: ${{ github.ref == 'refs/heads/development' }}
    needs: [ sonar ]
    steps:
      - uses: actions/checkout@v2     
      -  name: Login to registry
         uses: docker/login-action@v1
         with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PWD }}
    
      - name: Build the Docker image    
        run: |
             docker login ${{ secrets.REGISTRY_HOST }}
             docker build . --tag ${{ secrets.REGISTRY_HOST }}/${GITHUB_REF##*/}/sigpae-frontend
             docker push ${{ secrets.REGISTRY_HOST }}/${GITHUB_REF##*/}/sigpae-frontend
             
      - name: send failure message
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: -571051431
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            💥 Failed in ${{ github.ref_name	}}!
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}            
            Repository: ${{ github.repository }}            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            Actions: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
             
  deploy:
  
    runs-on: self-hosted
    needs: [ build ]
    if: ${{ github.ref == 'refs/heads/development' }}        
    environment:
      name: development
    steps:
      - name: Redeploy
        uses: luizhpriotto/action_images@kubectl-v2.0
        env: 
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
          NAMESPACE: sme-sigpae
          WORKLOAD: sigpae-frontend
          
      - name: send failure message
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: -571051431
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            💥 Failed in ${{ github.ref_name	}}!
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}            
            Repository: ${{ github.repository }}            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            Actions: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
      - name: send success message
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: -571051431
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚀 Success in ${{ github.ref_name	}}!
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}            
            Repository: ${{ github.repository }}            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            Actions: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
